### ISSUE TITLE
Bug: sorting commands should leave frontmatter intact

### ISSUE THREAD

**Issue by jamesx4** [usernamehw/vscode-todo-md#85] opened 2023-12-18 17:21 UTC
When using any of the _Todo MD_ sort commands, frontmatter should always be preserved if present in any of the files matching the Activate Pattern. Currently, the todo file is completely rewritten for the sort (to be expected), but the frontmatter is lost.  

This is important for systems like Dendron or any other system user's may come up with that utilizes frontmatter. 

Frontmatter being of the form:
```
---
property: value
---
```

**Comment by usernamehw** [comment] 2023-12-19 09:59
Duplicate of #71

**Closed by usernamehw** 2023-12-19 09:59 UTC
